package com.matrimony.backend.enums;

public enum NotificationType {
    INTEREST_RECEIVED,
    INTEREST_ACCEPTED,
    INTEREST_DECLINED,
    PROFILE_VIEWED,
    CONTACT_REQUEST,
    CONTACT_REQUEST_APPROVED,
    NEW_MESSAGE,
    PHOTO_APPROVED,
    PHOTO_REJECTED,
    PROFILE_APPROVED,
    PROFILE_REJECTED,
    SUBSCRIPTION_EXPIRING,
    PAYMENT_APPROVED,
    PAYMENT_UNDERPAID,
    PAYMENT_REJECTED,
    SYSTEM
}
