CREATE TABLE matrimony_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    profile_created_for VARCHAR(30) NOT NULL,
    first_name VARCHAR(80) NOT NULL,
    middle_name VARCHAR(80) NULL,
    last_name VARCHAR(80) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    date_of_birth DATE NULL,
    height_in_cm INT NULL,
    weight_in_kg INT NULL,
    marital_status VARCHAR(40) NULL,
    number_of_children INT NULL,
    children_living_status VARCHAR(80) NULL,
    physical_status VARCHAR(80) NULL,
    mother_tongue VARCHAR(80) NULL,
    religion VARCHAR(80) NULL,
    community VARCHAR(80) NULL,
    sub_community VARCHAR(80) NULL,
    caste_no_bar BOOLEAN NULL,
    gothra VARCHAR(80) NULL,
    manglik_status VARCHAR(80) NULL,
    citizenship VARCHAR(80) NULL,
    country VARCHAR(80) NULL,
    state VARCHAR(80) NULL,
    district VARCHAR(80) NULL,
    city VARCHAR(80) NULL,
    postal_code VARCHAR(20) NULL,
    residency_status VARCHAR(80) NULL,
    about_me VARCHAR(2000) NULL,
    profile_status VARCHAR(40) NOT NULL,
    profile_completeness INT NOT NULL DEFAULT 0,
    last_active_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_profile_user UNIQUE (user_id),
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE education_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    highest_education VARCHAR(120) NULL,
    education_specialization VARCHAR(120) NULL,
    college_name VARCHAR(180) NULL,
    additional_qualification VARCHAR(180) NULL,
    CONSTRAINT uk_education_profile UNIQUE (profile_id),
    CONSTRAINT fk_education_profile FOREIGN KEY (profile_id) REFERENCES matrimony_profiles(id)
);

CREATE TABLE career_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    employed_in VARCHAR(255) NULL,
    occupation VARCHAR(120) NULL,
    company_name VARCHAR(180) NULL,
    job_title VARCHAR(120) NULL,
    annual_income DECIMAL(14,2) NULL,
    income_currency VARCHAR(10) NULL,
    work_country VARCHAR(80) NULL,
    work_state VARCHAR(80) NULL,
    work_city VARCHAR(80) NULL,
    CONSTRAINT uk_career_profile UNIQUE (profile_id),
    CONSTRAINT fk_career_profile FOREIGN KEY (profile_id) REFERENCES matrimony_profiles(id)
);

CREATE TABLE family_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    family_type VARCHAR(255) NULL,
    family_status VARCHAR(255) NULL,
    family_values VARCHAR(255) NULL,
    father_status VARCHAR(255) NULL,
    father_occupation VARCHAR(255) NULL,
    mother_status VARCHAR(255) NULL,
    mother_occupation VARCHAR(255) NULL,
    number_of_brothers INT NULL,
    married_brothers INT NULL,
    number_of_sisters INT NULL,
    married_sisters INT NULL,
    family_country VARCHAR(255) NULL,
    family_state VARCHAR(255) NULL,
    family_city VARCHAR(255) NULL,
    family_description VARCHAR(1200) NULL,
    CONSTRAINT uk_family_profile UNIQUE (profile_id),
    CONSTRAINT fk_family_profile FOREIGN KEY (profile_id) REFERENCES matrimony_profiles(id)
);

CREATE TABLE lifestyle_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    diet VARCHAR(255) NULL,
    smoking_habit VARCHAR(255) NULL,
    drinking_habit VARCHAR(255) NULL,
    hobbies VARCHAR(1000) NULL,
    interests VARCHAR(1000) NULL,
    languages_known VARCHAR(1000) NULL,
    CONSTRAINT uk_lifestyle_profile UNIQUE (profile_id),
    CONSTRAINT fk_lifestyle_profile FOREIGN KEY (profile_id) REFERENCES matrimony_profiles(id)
);

CREATE TABLE horoscope_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    date_of_birth DATE NULL,
    time_of_birth TIME NULL,
    place_of_birth VARCHAR(255) NULL,
    rashi VARCHAR(255) NULL,
    nakshatra VARCHAR(255) NULL,
    manglik_status VARCHAR(255) NULL,
    horoscope_available BOOLEAN NULL,
    horoscope_document_url VARCHAR(255) NULL,
    CONSTRAINT uk_horoscope_profile UNIQUE (profile_id),
    CONSTRAINT fk_horoscope_profile FOREIGN KEY (profile_id) REFERENCES matrimony_profiles(id)
);
