CREATE TABLE partner_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    minimum_age INT NULL,
    maximum_age INT NULL,
    minimum_height INT NULL,
    maximum_height INT NULL,
    minimum_income DECIMAL(38,2) NULL,
    maximum_income DECIMAL(38,2) NULL,
    description VARCHAR(1200) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_partner_preference_profile UNIQUE (profile_id),
    CONSTRAINT fk_partner_preference_profile FOREIGN KEY (profile_id) REFERENCES matrimony_profiles(id)
);

CREATE TABLE partner_preference_marital_statuses (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_religions (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_communities (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_sub_communities (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_mother_tongues (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_countries (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_states (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_cities (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_education_levels (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_occupations (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_diets (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_physical_statuses (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));
CREATE TABLE partner_preference_manglik (preference_id BIGINT NOT NULL, preference_value VARCHAR(255));

CREATE TABLE profile_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    photo_url VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(255) NULL,
    primary_photo BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INT NOT NULL DEFAULT 0,
    privacy_level VARCHAR(40) NOT NULL,
    moderation_status VARCHAR(40) NOT NULL,
    rejection_reason VARCHAR(800) NULL,
    uploaded_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP NULL,
    approved_by BIGINT NULL,
    CONSTRAINT fk_photo_profile FOREIGN KEY (profile_id) REFERENCES matrimony_profiles(id),
    CONSTRAINT fk_photo_approved_by FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE profile_privacy_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    profile_visibility VARCHAR(50) NOT NULL,
    photo_visibility VARCHAR(50) NOT NULL,
    contact_visibility VARCHAR(50) NOT NULL,
    date_of_birth_visibility VARCHAR(50) NOT NULL,
    income_visibility VARCHAR(50) NOT NULL,
    horoscope_visibility VARCHAR(50) NOT NULL,
    allow_profile_views BOOLEAN NOT NULL,
    allow_messages BOOLEAN NOT NULL,
    allow_contact_requests BOOLEAN NOT NULL,
    show_online_status BOOLEAN NOT NULL,
    show_last_active BOOLEAN NOT NULL,
    CONSTRAINT uk_privacy_profile UNIQUE (profile_id),
    CONSTRAINT fk_privacy_profile FOREIGN KEY (profile_id) REFERENCES matrimony_profiles(id)
);
